name: Build executable from python project

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Check-out repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
        installer-parallel: true

    - name: Install Dependencies
      run: |
        poetry install --without=dev
        poetry add pyinstaller

    - name: Build Executable pyinstaller
      run: |
        pyinstaller linux.spec

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_ubuntu
        path: |
            dist/transformator-linux

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
        installer-parallel: true

    - name: Install Dependencies
      run: |
        poetry install --without=dev
        poetry add pyinstaller

    - name: Build Executable pyinstaller
      run: |
        pyinstaller windows.spec

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_windows
        path: |
            dist/transformator-windows.exe

  release:
    name: Create Release
    permissions:
      contents: write
    needs:
      - build-ubuntu
      - build-windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*
